# Site settings
title: Greg Dutcher's Blog
email: greg.dutcher@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Greg Dutcher's blog on art and technology
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gregdutcher.githubpages.io" # the base hostname & protocol for your site
github_username:  syntactical

# Build settings
markdown: kramdown
